-- Add building_structure_id column to connected_carparks
-- This stores the BUILDINGSTRUCTUREID from the HK Government Building Footprint dataset
-- Used to filter the 3D building overlay to show only the selected carpark's building

ALTER TABLE connected_carparks
ADD COLUMN IF NOT EXISTS building_structure_id TEXT;

-- Update with spatial join results (131/132 carparks matched)
-- Generated by scripts/find-connected-carpark-buildings.py

UPDATE connected_carparks SET building_structure_id = '223799' WHERE park_id = 'connected_2'; -- 909 Cheung Sha Wan Road
UPDATE connected_carparks SET building_structure_id = '398501' WHERE park_id = 'connected_3'; -- Admiralty Car Park
UPDATE connected_carparks SET building_structure_id = '143303' WHERE park_id = 'connected_4'; -- AEON Lai Chi Kok Store
UPDATE connected_carparks SET building_structure_id = '152936' WHERE park_id = 'connected_131'; -- Airport Carpark 4
UPDATE connected_carparks SET building_structure_id = '213596' WHERE park_id = 'connected_5'; -- apm
UPDATE connected_carparks SET building_structure_id = '211611' WHERE park_id = 'connected_6'; -- Austin Tower
UPDATE connected_carparks SET building_structure_id = '128739' WHERE park_id = 'connected_7'; -- Bellagio Visitor Car Park
UPDATE connected_carparks SET building_structure_id = '209328' WHERE park_id = 'connected_8'; -- Blossom Garden
UPDATE connected_carparks SET building_structure_id = '207462' WHERE park_id = 'connected_9'; -- Botania Villa
UPDATE connected_carparks SET building_structure_id = '145928' WHERE park_id = 'connected_10'; -- Brill Plaza
UPDATE connected_carparks SET building_structure_id = '143184' WHERE park_id = 'connected_11'; -- Capital Building
UPDATE connected_carparks SET building_structure_id = '123633' WHERE park_id = 'connected_12'; -- Castello
UPDATE connected_carparks SET building_structure_id = '84645' WHERE park_id = 'connected_13'; -- CCT Telecom Building
UPDATE connected_carparks SET building_structure_id = '145095' WHERE park_id = 'connected_14'; -- Centre Parc
UPDATE connected_carparks SET building_structure_id = '209346' WHERE park_id = 'connected_15'; -- Chelsea Heights
UPDATE connected_carparks SET building_structure_id = '209808' WHERE park_id = 'connected_16'; -- Chi Fu Landmark
UPDATE connected_carparks SET building_structure_id = '435022' WHERE park_id = 'connected_17'; -- Chi Shin Street Carpark
UPDATE connected_carparks SET building_structure_id = '168537' WHERE park_id = 'connected_18'; -- China Hong Kong City
UPDATE connected_carparks SET building_structure_id = '121729' WHERE park_id = 'connected_19'; -- Chinachem Tsuen Wan Plaza
UPDATE connected_carparks SET building_structure_id = '415276' WHERE park_id = 'connected_20'; -- Citygateoutlets P2
UPDATE connected_carparks SET building_structure_id = '213320' WHERE park_id = 'connected_21'; -- Cityplaza
UPDATE connected_carparks SET building_structure_id = '225892' WHERE park_id = 'connected_22'; -- Citywalk
UPDATE connected_carparks SET building_structure_id = '159616' WHERE park_id = 'connected_23'; -- Coda Plaza
UPDATE connected_carparks SET building_structure_id = '201976' WHERE park_id = 'connected_24'; -- Concord Square
UPDATE connected_carparks SET building_structure_id = '211773' WHERE park_id = 'connected_132'; -- Concordia Plaza
UPDATE connected_carparks SET building_structure_id = '374175' WHERE park_id = 'connected_25'; -- Cos Centre
UPDATE connected_carparks SET building_structure_id = '208350' WHERE park_id = 'connected_26'; -- East Point City
UPDATE connected_carparks SET building_structure_id = '178697' WHERE park_id = 'connected_27'; -- East Town Building
UPDATE connected_carparks SET building_structure_id = '171367' WHERE park_id = 'connected_1'; -- Eight Commercial Tower
UPDATE connected_carparks SET building_structure_id = '395930' WHERE park_id = 'connected_28'; -- Eight Regency
UPDATE connected_carparks SET building_structure_id = '203869' WHERE park_id = 'connected_29'; -- Eightland Gardens
UPDATE connected_carparks SET building_structure_id = '209352' WHERE park_id = 'connected_30'; -- Eldo Garden
UPDATE connected_carparks SET building_structure_id = '50406' WHERE park_id = 'connected_31'; -- Evergreen Court
UPDATE connected_carparks SET building_structure_id = '69412' WHERE park_id = 'connected_32'; -- Fortune Plaza
UPDATE connected_carparks SET building_structure_id = '201547' WHERE park_id = 'connected_33'; -- Fu Shing Building
UPDATE connected_carparks SET building_structure_id = '4926' WHERE park_id = 'connected_34'; -- Fung Nam Road Car Park
UPDATE connected_carparks SET building_structure_id = '105985' WHERE park_id = 'connected_35'; -- Grandway Garden
UPDATE connected_carparks SET building_structure_id = '212425' WHERE park_id = 'connected_36'; -- Harbour Heights (Open Space) Car Park
UPDATE connected_carparks SET building_structure_id = '391509' WHERE park_id = 'connected_37'; -- Harbour North
UPDATE connected_carparks SET building_structure_id = '204141' WHERE park_id = 'connected_38'; -- Harbour Pinnacle
UPDATE connected_carparks SET building_structure_id = '120992' WHERE park_id = 'connected_39'; -- HI-Tech Industrial Centre
UPDATE connected_carparks SET building_structure_id = '203277' WHERE park_id = 'connected_40'; -- Ho Shun Tai Building
UPDATE connected_carparks SET building_structure_id = '118975' WHERE park_id = 'connected_41'; -- HomeSquare
UPDATE connected_carparks SET building_structure_id = '209733' WHERE park_id = 'connected_42'; -- Hong Kong Plaza
UPDATE connected_carparks SET building_structure_id = '209348' WHERE park_id = 'connected_43'; -- Hong Lai Gardens
UPDATE connected_carparks SET building_structure_id = '213873' WHERE park_id = 'connected_44'; -- Honour Industrial Centre
UPDATE connected_carparks SET building_structure_id = '142395' WHERE park_id = 'connected_45'; -- HSBC Centre
UPDATE connected_carparks SET building_structure_id = '125521' WHERE park_id = 'connected_46'; -- International Trade Centre
UPDATE connected_carparks SET building_structure_id = '209351' WHERE park_id = 'connected_51'; -- K-Point
UPDATE connected_carparks SET building_structure_id = '164097' WHERE park_id = 'connected_47'; -- Kimberley Road
UPDATE connected_carparks SET building_structure_id = '353567' WHERE park_id = 'connected_48'; -- King Palace Plaza
UPDATE connected_carparks SET building_structure_id = '379299' WHERE park_id = 'connected_49'; -- Kings Wing Plaza II
UPDATE connected_carparks SET building_structure_id = '436168' WHERE park_id = 'connected_50'; -- Kodak House II
UPDATE connected_carparks SET building_structure_id = '205248' WHERE park_id = 'connected_52'; -- Kwai Fong Court
UPDATE connected_carparks SET building_structure_id = '408163' WHERE park_id = 'connected_53'; -- Kwai Sing Centre
UPDATE connected_carparks SET building_structure_id = '202018' WHERE park_id = 'connected_54'; -- Lai Bo Garden
UPDATE connected_carparks SET building_structure_id = '18604' WHERE park_id = 'connected_55'; -- Landmark North
UPDATE connected_carparks SET building_structure_id = '209742' WHERE park_id = 'connected_56'; -- Lun Fung Court
UPDATE connected_carparks SET building_structure_id = '202003' WHERE park_id = 'connected_57'; -- Maritime Square 1
UPDATE connected_carparks SET building_structure_id = '214278' WHERE park_id = 'connected_58'; -- Mei Foo Sun Chuen-S7
UPDATE connected_carparks SET building_structure_id = '136992' WHERE park_id = 'connected_59'; -- Metroplaza
UPDATE connected_carparks SET building_structure_id = '203516' WHERE park_id = 'connected_60'; -- Metropolis Plaza
UPDATE connected_carparks SET building_structure_id = '345869' WHERE park_id = 'connected_61'; -- Mikiki
UPDATE connected_carparks SET building_structure_id = '160880' WHERE park_id = 'connected_62'; -- Millennium City 1
UPDATE connected_carparks SET building_structure_id = '213363' WHERE park_id = 'connected_63'; -- Millennium City 2 & 3
UPDATE connected_carparks SET building_structure_id = '226978' WHERE park_id = 'connected_64'; -- Millennium City 6
UPDATE connected_carparks SET building_structure_id = '211487' WHERE park_id = 'connected_65'; -- Moko
UPDATE connected_carparks SET building_structure_id = '205058' WHERE park_id = 'connected_66'; -- Nan Fung Commercial Centre
UPDATE connected_carparks SET building_structure_id = '84808' WHERE park_id = 'connected_67'; -- New Commerce Centre
UPDATE connected_carparks SET building_structure_id = '211771' WHERE park_id = 'connected_68'; -- New Mandarin Plaza
UPDATE connected_carparks SET building_structure_id = '123798' WHERE park_id = 'connected_69'; -- New Tech Plaza
UPDATE connected_carparks SET building_structure_id = '111997' WHERE park_id = 'connected_70'; -- New Town Mansion
UPDATE connected_carparks SET building_structure_id = '99695' WHERE park_id = 'connected_71'; -- New Town Plaza Phase 1
UPDATE connected_carparks SET building_structure_id = '213078' WHERE park_id = 'connected_72'; -- New Trade Plaza
UPDATE connected_carparks SET building_structure_id = '204812' WHERE park_id = 'connected_73'; -- Nina Mall
UPDATE connected_carparks SET building_structure_id = '152936' WHERE park_id = 'connected_74'; -- Number 4 Multi-Storey Carpark
UPDATE connected_carparks SET building_structure_id = '210831' WHERE park_id = 'connected_75'; -- Olympian City 2
UPDATE connected_carparks SET building_structure_id = '211534' WHERE park_id = 'connected_76'; -- Onbury Car Park
UPDATE connected_carparks SET building_structure_id = '213432' WHERE park_id = 'connected_77'; -- One Sky Parc
UPDATE connected_carparks SET building_structure_id = '204971' WHERE park_id = 'connected_78'; -- Pacific Place
UPDATE connected_carparks SET building_structure_id = '213925' WHERE park_id = 'connected_79'; -- Park Central
UPDATE connected_carparks SET building_structure_id = '205022' WHERE park_id = 'connected_80'; -- Peninsula Square
UPDATE connected_carparks SET building_structure_id = '127846' WHERE park_id = 'connected_81'; -- Peninsula Tower
UPDATE connected_carparks SET building_structure_id = '407276' WHERE park_id = 'connected_82'; -- Plaza 88
UPDATE connected_carparks SET building_structure_id = '205946' WHERE park_id = 'connected_83'; -- Po Sing Centre
UPDATE connected_carparks SET building_structure_id = '99521' WHERE park_id = 'connected_84'; -- Po Tai Street Car Park
UPDATE connected_carparks SET building_structure_id = '348626' WHERE park_id = 'connected_85'; -- Popcorn 1
UPDATE connected_carparks SET building_structure_id = '364090' WHERE park_id = 'connected_86'; -- PopWalk
UPDATE connected_carparks SET building_structure_id = '389313' WHERE park_id = 'connected_87'; -- Port 33
UPDATE connected_carparks SET building_structure_id = '103479' WHERE park_id = 'connected_88'; -- Sai Kung Garden
UPDATE connected_carparks SET building_structure_id = '99815' WHERE park_id = 'connected_89'; -- Sai Kung Town Centre
UPDATE connected_carparks SET building_structure_id = '165658' WHERE park_id = 'connected_90'; -- Shanghai Industrial Investment Building
UPDATE connected_carparks SET building_structure_id = '212730' WHERE park_id = 'connected_91'; -- Shatin Park Stage 1
UPDATE connected_carparks SET building_structure_id = '426921' WHERE park_id = 'connected_92'; -- Shell Airport Cargo Terminal
UPDATE connected_carparks SET building_structure_id = '206079' WHERE park_id = 'connected_93'; -- Siu On Centre
UPDATE connected_carparks SET building_structure_id = '201979' WHERE park_id = 'connected_94'; -- Skyline Plaza
UPDATE connected_carparks SET building_structure_id = '427845' WHERE park_id = 'connected_95'; -- SOHO West
UPDATE connected_carparks SET building_structure_id = '170362' WHERE park_id = 'connected_96'; -- Sun Hung Kai Centre
UPDATE connected_carparks SET building_structure_id = '223568' WHERE park_id = 'connected_97'; -- Sun Kwai Hing Plaza
UPDATE connected_carparks SET building_structure_id = '213143' WHERE park_id = 'connected_98'; -- Sunway Gardens
UPDATE connected_carparks SET building_structure_id = '203963' WHERE park_id = 'connected_99'; -- Tai Po Mega Mall
UPDATE connected_carparks SET building_structure_id = '205095' WHERE park_id = 'connected_100'; -- Tak Bo Garden
UPDATE connected_carparks SET building_structure_id = '213191' WHERE park_id = 'connected_101'; -- Telford Plaza
UPDATE connected_carparks SET building_structure_id = '412334' WHERE park_id = 'connected_102'; -- The Lohas
UPDATE connected_carparks SET building_structure_id = '433345' WHERE park_id = 'connected_103'; -- The Southside
UPDATE connected_carparks SET building_structure_id = '203948' WHERE park_id = 'connected_104'; -- The Sun Arcade
UPDATE connected_carparks SET building_structure_id = '425278' WHERE park_id = 'connected_105'; -- The Wai
UPDATE connected_carparks SET building_structure_id = '165800' WHERE park_id = 'connected_106'; -- Three Pacific Place
UPDATE connected_carparks SET building_structure_id = '201933' WHERE park_id = 'connected_107'; -- Thriving Industrial Centre
UPDATE connected_carparks SET building_structure_id = '168201' WHERE park_id = 'connected_108'; -- Times Square
UPDATE connected_carparks SET building_structure_id = '205090' WHERE park_id = 'connected_109'; -- Tonic Industrial Centre
UPDATE connected_carparks SET building_structure_id = '101546' WHERE park_id = 'connected_110'; -- Tsuen Kam Centre
UPDATE connected_carparks SET building_structure_id = '104377' WHERE park_id = 'connected_111'; -- Tsuen Wan Centre
UPDATE connected_carparks SET building_structure_id = '209545' WHERE park_id = 'connected_112'; -- Tsuen Wan Plaza
UPDATE connected_carparks SET building_structure_id = '209363' WHERE park_id = 'connected_113'; -- Tuen Mun Town Plaza
UPDATE connected_carparks SET building_structure_id = '151524' WHERE park_id = 'connected_114'; -- Two Sky Parc
UPDATE connected_carparks SET building_structure_id = '62349' WHERE park_id = 'connected_115'; -- Uptown Plaza
UPDATE connected_carparks SET building_structure_id = '357270' WHERE park_id = 'connected_116'; -- V City
UPDATE connected_carparks SET building_structure_id = '396577' WHERE park_id = 'connected_117'; -- V Walk
UPDATE connected_carparks SET building_structure_id = '212388' WHERE park_id = 'connected_118'; -- Victoria Centre
UPDATE connected_carparks SET building_structure_id = '179491' WHERE park_id = 'connected_119'; -- Viking Gardens
UPDATE connected_carparks SET building_structure_id = '209780' WHERE park_id = 'connected_120'; -- Wah Ming Centre
UPDATE connected_carparks SET building_structure_id = '108123' WHERE park_id = 'connected_121'; -- Wai Wah Centre
UPDATE connected_carparks SET building_structure_id = '154679' WHERE park_id = 'connected_122'; -- Wang Kwong Road Car Park
UPDATE connected_carparks SET building_structure_id = '205565' WHERE park_id = 'connected_123'; -- Wealthy Garden
UPDATE connected_carparks SET building_structure_id = '417497' WHERE park_id = 'connected_124'; -- Wetland Public Vehicle Park
UPDATE connected_carparks SET building_structure_id = '161143' WHERE park_id = 'connected_126'; -- wwwtc mall
UPDATE connected_carparks SET building_structure_id = '203952' WHERE park_id = 'connected_127'; -- YF Life Tower
UPDATE connected_carparks SET building_structure_id = '387365' WHERE park_id = 'connected_128'; -- YOHO Mall
UPDATE connected_carparks SET building_structure_id = '201529' WHERE park_id = 'connected_129'; -- Yuen Long Hop Yick Plaza
UPDATE connected_carparks SET building_structure_id = '201497' WHERE park_id = 'connected_130'; -- Yuen Long Plaza

-- Note: connected_125 (Wu Shan Road Car Park) has no building match - standalone open car park

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_connected_carparks_building_structure_id ON connected_carparks(building_structure_id);
